# Generated by Django 5.2 on 2025-05-06 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_shirt'),
    ]

    operations = [
        migrations.AddField(
            model_name='shirt',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='shirt',
            name='image',
            field=models.ImageField(upload_to='shirts/'),
        ),
    ]
