# Generated by Django 5.2 on 2025-05-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='care',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='composition',
            field=models.TextField(blank=True),
        ),
    ]
